name: PHPStan

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    phpstan:
        name: "PHPStan ${{ matrix.php-version }}"

        runs-on: ubuntu-latest
        strategy:
            matrix:
                php_version: [8.1]

        steps:
            -   uses: actions/checkout@v2

            -   name: "Install dependencies with Composer"
                uses: php-actions/composer@v5
                with:
                    php_version: ${{ matrix.php_version }}
                    version: 2
                    args: --profile --ignore-platform-reqs

            -   name: 'PHPStan Static Analysis'
                uses: php-actions/phpstan@v2
                with:
                    configuration: tests/phpstan.neon
                    memory_limit: 256M
