name: Validate

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    php-coding-standard:
        name: "PHP Coding Standard ${{ matrix.php-version }}"

        runs-on: ubuntu-latest
        strategy:
            matrix:
                php_version: [8.1]

        steps:
            -   uses: actions/checkout@v2

            -   name: 'Validate composer.json'
                run: composer validate

            -   name: 'Cache Composer packages'
                id: composer-cache
                uses: actions/cache@v4
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: 'Install dependencies with Composer'
                uses: php-actions/composer@v5
                with:
                    php_version: ${{ matrix.php_version }}
                    version: 2
                    args: --profile --ignore-platform-reqs

            -   name: 'PHP CodeSniffer Validations'
                run: vendor/bin/phpcs
